# -*- coding: utf-8 -*-
"""Aula 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IuR7Q07_FUNvQ-8LSwhkiLn7WL-MFtoy
"""

#Apenas um comentario, bote um "#"
y = "Em Python, não é necessário dizer o tipo da variável, ele automaticamente atribui quando colocamos o valor dela"
print(y)

print("não precisa de ;")

"""É utilizado para saber o tipo da variavel :


"""

type(y)

for x in range(5): 
  print(x)
  if(x==1):
    print("Um")
  if(x==2):
    print("Dois")
  if(x==3):
    print("Três")
  if(x==4):
    print("Quatro")
  if(x==0):
    print("Zero")

"""Criação de listas:"""

listao = [0,1,2,3,4]
listinha = list(range(5))
listaVazia = []
print(listao)
print(listinha)
print(listaVazia)
print(type(listao))

"""Comandos da lista:"""

listao.append(5)
print(listao)

listao[1] = 1.5
print(listao)

listao.insert(1, 100)
print(listao)

listao.reverse()
print(listao)

"""Colocar em ordem alfabetica ou crescente:"""

listao.sort()
print(listao)

listao.count(1)

listao.index(100)

print(listao)
print(listao[1:4])
print(listao[0:6:2])
print("Nesse ultimo ele mostra a lista do elemento 0 ao 5 mostrando uma palavra a cada 2")

tuflao=(7, "João", 'Vitor') #n é possivel alterar os valores da tufla depois
print(tuflao)

listahehe=[7, "João", 'Vitor']
print(listahehe)

dicionarao = {} #não é possivel mudar os valores do dicionario
dicionarao['Joao']=10
dicionarao['Vitor']=10
dicionarao['Oliveira']=10
dicionarao['legal']=9
print(dicionarao)

dicionarao['legal']

print(dicionarao.keys())

print(dicionarao.values())

list(dicionarao.keys())[0]

list(dicionarao.items())

for nome, nota in dicionarao.items():
  print(nome, "tirou", nota)

"""arquivo_entrada = open("/content/drive/MyDrive/Aula de Python/Teste.txt", 'r') -- ler

arquivo_entrada = open("/content/drive/MyDrive/Aula de Python/Teste.txt", 'w') --escrever (acho q apaga oq tinha)

arquivo_entrada = open("/content/drive/MyDrive/Aula de Python/Teste.txt", 'a') -- adiciona texto novo no vim do texto que ja existe
"""

arqEscrita = open("/content/drive/MyDrive/AulaDePython/Teste.txt", 'w')
arqEscrita.write("teste")
arqEscrita.close()

arqTeste = open("/content/drive/MyDrive/AulaDePython/Teste.txt", 'r')
print(arqTeste.read())
arqTeste.close()

arqEscrita = open("/content/drive/MyDrive/AulaDePython/Teste.txt", 'a')
arqEscrita.write(" adicionei outro teste")
arqEscrita.close()

arqTeste = open("/content/drive/MyDrive/AulaDePython/Teste.txt", 'r')
print(arqTeste.read())
arqTeste.close()

arqEscrita = open("/content/drive/MyDrive/AulaDePython/Teste.txt", 'a')
numero = 7
arqEscrita.write(str(numero))
arqEscrita.close()

arqTeste = open("/content/drive/MyDrive/AulaDePython/Teste.txt", 'r')
print(arqTeste.read())
arqTeste.close()

string = "João Vitor"
print(string[0])
print(string[1:3])
print(string[2:])
print(string[:])
print(string[0:70])

tamanho = len(string)
print(tamanho)
print(string.upper())
print(string.lower())
print(string.replace('o', 'u'))
hehe=' Ola tudeo bem    '
hehe.strip()
print(hehe.strip())
print(string.split()) #se n tiver nd nos parenteses ele divide a partir dos espaços
print(string.split('o')) #ele usa oq ta dentro do parenteses como parametro pra dividir
tam = len(string.split()) #sabe o tamanho da lista de palavras q ele dividiu
print(tam) 
corte=(string.split())
colado= " ".join(corte) #junta as palavras da lista, adicionando espaço entre elas
print(colado)